<a href="https://colab.research.google.com/github/valeencamargo14/TP-Labo-/blob/Tincho/TP_Labo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### a) Cargar y mostrar los datos de los Datasets
Cargaremos el dataset en un DataFrame de pandas y mostraremos las primeras e últimas filas.

In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

RUTA = '/content/'  # carpeta donde están los CSV (Google Colab)
df_posiciones = pd.read_csv(RUTA + 'premier_league_posiciones_2005_2026.csv')
df_gastos = pd.read_csv(RUTA + 'premier_league_gastos_2005_2026.csv')

print('=== POSICIONES: primeras filas ===')
display(df_posiciones.head())
print('=== POSICIONES: últimas filas ===')
display(df_posiciones.tail())

print('=== GASTOS: primeras filas ===')
display(df_gastos.head())
print('=== GASTOS: últimas filas ===')
display(df_gastos.tail())

=== POSICIONES: primeras filas ===

  temporada               club  posicion  puntos  partidos  ganados  empatados  perdidos  goles_favor  goles_contra  dif_goles
0   2025-26         Arsenal FC         1      85        38       26          7         5           71            27         44
1   2025-26    Manchester City         2      78        38       23          9         6           77            35         42
2   2025-26  Manchester United         3      71        38       20         11         7           69            50         19
3   2025-26        Aston Villa         4      65        38       19          8        11           56            49          7
4   2025-26       Liverpool FC         5      60        38       17          9        12           63            53         10

=== POSICIONES: últimas filas ===

    temporada                  club  posicion  puntos  partidos  ganados  empatados  perdidos  goles_favor  goles_contra  dif_goles
415   2005-06           Aston Villa        16      42        38       10         12        16           42            55        -13
416   2005-06         Portsmouth FC        17      38        38       10          8        20           37            62        -25
417   2005-06       Birmingham City        18      34        38        8         10        20           28            50        -22
418   2005-06  West Bromwich Albion        19      30        38        7          9        22           31            58        -27
419   2005-06        Sunderland AFC        20      15        38        3          6        29           26            69        -43

=== GASTOS: primeras filas ===

  temporada              club  gasto_bruto  altas  ingresos  bajas  balance  gasto_neto
0   2025-26      Liverpool FC       483.13     20    219.50     12  -263.63      263.63
1   2025-26        Chelsea FC       329.15     34    339.25     29    10.10      -10.10
2   2025-26   Manchester City       301.80     26    107.28     20  -194.52      194.52
3   2025-26        Arsenal FC       297.57     21     13.88     17  -283.69      283.69
4   2025-26  Newcastle United       278.85     16    176.00     16  -102.85      102.85

=== GASTOS: últimas filas ===

    temporada               club  gasto_bruto  altas  ingresos  bajas  balance  gasto_neto
415   2005-06   Blackburn Rovers         9.40     23     2.700     25    -6.70        6.70
416   2005-06  Charlton Athletic         9.10     31     5.710     23    -3.39        3.39
417   2005-06     Sunderland AFC         6.33     25     0.325     27    -6.00        6.00
418   2005-06   Bolton Wanderers         6.20     13     0.000     17    -6.20        6.20
419   2005-06          Fulham FC         5.95     25     4.630     24    -1.33        1.33

### b) Estructura de los Datasets
Analizaremos las dimensiones, tipos de datos y cobertura temporal de los datos cargados.

In [16]:
for nombre, df in [('POSICIONES', df_posiciones), ('GASTOS', df_gastos)]:
    print(f'=== {nombre} ===')
    print(f'Dimensiones: {df.shape[0]} filas x {df.shape[1]} columnas')
    print(f'Columnas: {list(df.columns)}')
    print('\nTipos de datos (.dtypes):')
    print(df.dtypes)
    print()

=== POSICIONES ===
Dimensiones: 420 filas x 11 columnas
Columnas: ['temporada', 'club', 'posicion', 'puntos', 'partidos', 'ganados', 'empatados', 'perdidos', 'goles_favor', 'goles_contra', 'dif_goles']

Tipos de datos (.dtypes):
temporada       object
club            object
posicion         int64
puntos           int64
partidos         int64
ganados          int64
empatados        int64
perdidos         int64
goles_favor      int64
goles_contra     int64
dif_goles        int64
dtype: object

=== GASTOS ===
Dimensiones: 420 filas x 8 columnas
Columnas: ['temporada', 'club', 'gasto_bruto', 'altas', 'ingresos', 'bajas', 'balance', 'gasto_neto']

Tipos de datos (.dtypes):
temporada       object
club            object
gasto_bruto    float64
altas            int64
ingresos       float64
bajas            int64
balance        float64
gasto_neto     float64
dtype: object

### c) Calidad de los Datos y Estadísticas Descriptivas
Evaluaremos la presencia de valores nulos, registros duplicados y generaremos las estadísticas descriptivas.

In [17]:
temporadas = sorted(df_posiciones['temporada'].unique())
print('--- Cobertura temporal ---')
print(f'Temporadas: {len(temporadas)}, desde {temporadas[0]} hasta {temporadas[-1]}')
print('Clubes por temporada:', df_posiciones.groupby('temporada').size().unique())
print('Partidos por club y temporada:', df_posiciones['partidos'].unique())

print('\n--- Cobertura geográfica (clubes) ---')
apariciones = df_posiciones['club'].value_counts()
print(f'Clubes distintos: {len(apariciones)}')
print(f'Clubes presentes en las {len(temporadas)} temporadas: {(apariciones == len(temporadas)).sum()}')
display(apariciones.rename('temporadas_en_la_liga').to_frame())

--- Cobertura temporal ---
Temporadas: 21, desde 2005-06 hasta 2025-26
Clubes por temporada: [20]
Partidos por club y temporada: [38]

--- Cobertura geográfica (clubes) ---
Clubes distintos: 44
Clubes presentes en las 21 temporadas: 7

                         temporadas_en_la_liga
club
Arsenal FC                                  21
Manchester City                             21
Manchester United                           21
Liverpool FC                                21
Chelsea FC                                  21
Everton FC                                  21
Tottenham Hotspur                           21
West Ham United                             20
Newcastle United                            19
Aston Villa                                 18
Fulham FC                                   15
Crystal Palace                              13
Southampton FC                              12
Sunderland AFC                              12
West Bromwich Albion                        11
Wolverhampton Wanderers                     11
Leicester City                              10
Stoke City                                  10
Burnley FC                                  10
AFC Bournemouth                              9
Brighton & Hove Albion                       9
Wigan Athletic                               8
Bolton Wanderers                             7
Watford FC                                   7
Blackburn Rovers                             7
Swansea City                                 7
Norwich City                                 6
Brentford FC                                 5
Middlesbrough FC                             5
Portsmouth FC                                5
Hull City                                    5
Birmingham City                              4
Nottingham Forest                            4
Leeds United                                 4
Sheffield United                             4
FC Reading                                   3
Queens Park Rangers                          3
Charlton Athletic                            2
Huddersfield Town                            2
Cardiff City                                 2
Ipswich Town                                 1
Luton Town                                   1
Blackpool FC                                 1
Derby County                                 1

In [18]:
for nombre, df in [('POSICIONES', df_posiciones), ('GASTOS', df_gastos)]:
    print(f'=== {nombre} ===')
    print('Valores nulos por columna:')
    print(df.isnull().sum())
    print(f'\nFilas duplicadas (completas): {df.duplicated().sum()}')
    print(f"Duplicados por (temporada, club): {df.duplicated(['temporada', 'club']).sum()}\n")

=== POSICIONES ===
Valores nulos por columna:
temporada       0
club            0
posicion        0
puntos          0
partidos        0
ganados         0
empatados       0
perdidos        0
goles_favor     0
goles_contra    0
dif_goles       0
dtype: int64

Filas duplicadas (completas): 0
Duplicados por (temporada, club): 0

=== GASTOS ===
Valores nulos por columna:
temporada      0
club           0
gasto_bruto    0
altas          0
ingresos       0
bajas          0
balance        0
gasto_neto     0
dtype: int64

Filas duplicadas (completas): 0
Duplicados por (temporada, club): 0

In [19]:
print('=== POSICIONES ===')
display(df_posiciones.describe().round(2))
print('=== GASTOS ===')
display(df_gastos.describe().round(2))

=== POSICIONES ===

       posicion  puntos  partidos  ganados  empatados  perdidos  goles_favor  goles_contra  dif_goles
count    420.00  420.00     420.0   420.00     420.00    420.00       420.00        420.00     420.00
mean      10.50   52.33      38.0    14.38       9.24     14.38        52.12         52.12       0.00
std        5.77   17.65       0.0     6.13       2.83      5.79        16.49         13.56      26.98
min        1.00   11.00      38.0     1.00       2.00      1.00        20.00         22.00     -69.00
25%        5.75   40.00      38.0    10.00       7.00     10.00        40.00         43.00     -19.00
50%       10.50   49.00      38.0    13.00       9.00     15.00        48.00         52.00      -4.50
75%       15.25   64.25      38.0    18.25      11.00     19.00        62.00         60.00      16.50
max       20.00  100.00      38.0    32.00      18.00     30.00       106.00        104.00      79.00

=== GASTOS ===

       gasto_bruto   altas  ingresos   bajas  balance  gasto_neto
count       420.00  420.00    420.00  420.00   420.00      420.00
mean         78.41   24.50     40.09   22.10   -38.32       38.32
std          76.43    8.55     50.14    7.23    61.75       61.75
min           0.00    5.00      0.00    4.00  -562.39     -129.31
25%          25.82   18.00      5.60   17.00   -59.68        5.76
50%          55.01   23.00     23.73   21.50   -23.22       23.22
75%         107.04   30.00     53.83   27.00    -5.76       59.68
max         630.25   57.00    339.25   48.00   129.31      562.39

In [20]:
# 1) Ceros en columnas monetarias (posibles datos faltantes disfrazados)
print(f"Filas con ingresos = 0: {(df_gastos['ingresos'] == 0).sum()}")
print(f"Filas con gasto_bruto = 0: {(df_gastos['gasto_bruto'] == 0).sum()}")
display(df_gastos[(df_gastos['ingresos'] == 0) | (df_gastos['gasto_bruto'] == 0)]
        [['temporada', 'club', 'gasto_bruto', 'altas', 'ingresos', 'bajas']])

Filas con ingresos = 0: 21
Filas con gasto_bruto = 0: 1

    temporada               club  gasto_bruto  altas  ingresos  bajas
56    2023-24     Crystal Palace        67.80     11      0.00      9
73    2022-23    AFC Bournemouth        93.40     21      0.00     15
83    2021-22   Newcastle United       138.50     12      0.00     10
88    2021-22     Crystal Palace        85.62     14      0.00     15
94    2021-22       Leeds United        59.30     17      0.00     15
102   2020-21       Leeds United       127.80     17      0.00     17
110   2020-21   Sheffield United        62.70     17      0.00     19
117   2020-21          Fulham FC        37.25     26      0.00     24
154   2018-19       Cardiff City        51.20     18      0.00     20
159   2018-19  Tottenham Hotspur         0.00      5      5.35      4
179   2017-18    AFC Bournemouth        34.30     17      0.00     14
235   2014-15     Leicester City        22.86     31      0.00     24
238   2014-15         Burnley FC        12.62     24      0.00     23
249   2013-14     Crystal Palace        33.00     43      0.00     32
254   2013-14       Swansea City        26.61     24      0.00     21
258   2013-14         Stoke City         7.00     21      0.00     20
267   2012-13     Southampton FC        41.50     31      0.00     25
339   2009-10          Fulham FC         7.61     28      0.00     26
356   2008-09          Hull City        17.95     26      0.00     18
398   2006-07         FC Reading         8.53     27      0.00     17
412   2005-06   Middlesbrough FC        13.96     20      0.00     12
418   2005-06   Bolton Wanderers         6.20     13      0.00     17

In [26]:
# 2) Coherencia interna
dif_balance = (df_gastos['ingresos'] - df_gastos['gasto_bruto'] - df_gastos['balance']).abs()
print(f'balance distinto de ingresos - gasto_bruto: {(dif_balance > 0.05).sum()} filas')

print(f"\ndif_goles distinto de goles_favor - goles_contra: "
      f"{(df_posiciones['goles_favor'] - df_posiciones['goles_contra'] != df_posiciones['dif_goles']).sum()} filas")
print(f"ganados + empatados + perdidos distinto de partidos: "
      f"{(df_posiciones['ganados'] + df_posiciones['empatados'] + df_posiciones['perdidos'] != df_posiciones['partidos']).sum()} filas")

esperado = 3 * df_posiciones['ganados'] + df_posiciones['empatados']
print('\nFilas donde puntos != 3*ganados + empatados (sanciones):')
display(df_posiciones[df_posiciones['puntos'] != esperado]
        [['temporada', 'club', 'ganados', 'empatados', 'puntos']].assign(esperado=esperado))

goles = df_posiciones.groupby('temporada')[['goles_favor', 'goles_contra']].sum()
print(f'Temporadas donde la suma de goles a favor y en contra no coincide: {(goles.goles_favor != goles.goles_contra).sum()}')

balance distinto de ingresos - gasto_bruto: 0 filas

dif_goles distinto de goles_favor - goles_contra: 0 filas
ganados + empatados + perdidos distinto de partidos: 0 filas

Filas donde puntos != 3*ganados + empatados (sanciones):

    temporada               club  ganados  empatados  puntos  esperado
54    2023-24         Everton FC       13          9      40        48
56    2023-24  Nottingham Forest        9          9      32        36
339   2009-10      Portsmouth FC        7          7      19        28

Temporadas donde la suma de goles a favor y en contra no coincide: 0

Hay tres filas donde los puntos no coinciden con 3 por victoria más empates, y son sanciones reales de deduccion de puntos a los siguientes equipos:
*   Everton 2023-24: 40 puntos, en lugar de 48.
*   Nottingham Forest 2023-24: 32 puntos, en lugar de 36.
*   Portsmouth 2009-10: 19 puntos, en lugar de 28.